// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbevbE35_HPKieQaF97PJYJxgf_keqG00',
    appId: '1:983556623282:web:2ca85438bb1b0b7b66b2ab',
    messagingSenderId: '983556623282',
    projectId: 'expenses-tracker-9122f',
    authDomain: 'expenses-tracker-9122f.firebaseapp.com',
    storageBucket: 'expenses-tracker-9122f.firebasestorage.app',
    measurementId: 'G-94GFJX0XJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi3VppzJOU5V2GaypKFW0gSLsO6MvpHP0',
    appId: '1:983556623282:android:1da45cb4a3b1c1f966b2ab',
    messagingSenderId: '983556623282',
    projectId: 'expenses-tracker-9122f',
    storageBucket: 'expenses-tracker-9122f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVlvHRBk_0VdQuCp5R_TWt06ikdkwoh5k',
    appId: '1:983556623282:ios:ced053d6414d6a2b66b2ab',
    messagingSenderId: '983556623282',
    projectId: 'expenses-tracker-9122f',
    storageBucket: 'expenses-tracker-9122f.firebasestorage.app',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVlvHRBk_0VdQuCp5R_TWt06ikdkwoh5k',
    appId: '1:983556623282:ios:ced053d6414d6a2b66b2ab',
    messagingSenderId: '983556623282',
    projectId: 'expenses-tracker-9122f',
    storageBucket: 'expenses-tracker-9122f.firebasestorage.app',
    iosBundleId: 'com.example.expensesTracker',
  );
}
